spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_db  # Replace with your DB name, username, and password
    username: your_username       # Your PostgreSQL username
    password: your_password       # Your PostgreSQL password
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # You can use 'none', 'create', or 'validate' depending on your needs
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false   # Disable H2 console if you're switching to PostgreSQL
