
#This configuration file connects to our Recipe database in Postgres so that our api can do the proper manipulations
#such as adding an entry in the table or removing one, or changing one.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # Replace with your DB name, username, and password
    username: marwajam       #  PostgreSQL username
    password: ""       # there is no password
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  #
    show-sql: true
    properties:
      hibernate:
        format_sql: true
